### ISSUE TITLE
Unable to see search volumes.

### ISSUE THREAD

**Issue by AntonioRuizBogarin** [antoineeripret/google_search_console_search_volume#11]
I have installed and configured the addon, but it does not show search volumes in Search Console on the Performance menu.

**Comment by antoineeripret** [comment]
Hey @AntonioRuizBogarin, thanks for reporting the issue. 

I've just tried it and it works on my side. 

![image](https://user-images.githubusercontent.com/9512616/151147129-cc740b7a-17f8-48e7-943d-98f80375015a.png)

- Have you configured the country in the extension configuration? 
- If you have, please open GSC, and tell me what status codes you are getting if you search for "surf" in the Network panel. 

![image](https://user-images.githubusercontent.com/9512616/151147657-8b1bddfc-7d03-434a-b441-3f17d5c34b89.png)

Thanks :)

**Comment by AntonioRuizBogarin** [comment]
Thanks Antoine, now works with US and ES. Probably I forgot to save the country change. :-/

**Comment by antoineeripret** [comment]
@AntonioRuizBogarin: no problem. Do not hesitate to open the ticket again if you still have issues.
