### ISSUE TITLE
Volumenes incorrectos

### ISSUE THREAD

**Issue by evaolivares** [antoineeripret/google_search_console_search_volume#3]
Los volúmenes que devuelve son incorrectos, no cuadran con los volúmenes que da Keyword Surfer en las SERPS
![photo5888460949944382512](https://user-images.githubusercontent.com/85240098/120497531-c61e2900-c3be-11eb-8b1f-e3577171c998.jpg)
<img width="780" alt="Captura de Pantalla 2021-06-02 a les 16 23 05" src="https://user-images.githubusercontent.com/85240098/120497631-dafabc80-c3be-11eb-8698-e7a72c9b704b.png">

.

**Comment by antoineeripret** [comment]
@evaolivares: Gracias por tu feedback. 

Podrías:

- Recargar la página de GSC con el panel de herramientas para desarrolladores abierto
- Abrir la pestaña "Network"
- Buscar "keywordsur" en las peticiones
- Copiar la URL de la primera solicitud que te sale  

![image](https://user-images.githubusercontent.com/9512616/120499018-ffa36400-c3bf-11eb-9d6f-60031d5a1851.png)

Creo que el problema es que el país que has indicado en el paso de la configuración no se ha guardado bien, y por lo tanto te devuelve los volúmenes de otro país. 

Gracias,

**Comment by antoineeripret** [comment]
@evaolivares: problema arreglado :)
