### ISSUE TITLE
Add padding to improve cell spacing

### ISSUE THREAD

**Issue by Xyborg** [antoineeripret/google_search_console_search_volume#5]
![gsc_searchvolumes](https://user-images.githubusercontent.com/1560798/122213722-9facc300-ce7f-11eb-9340-a83db27d6745.png)
https://github.com/antoineeripret/google_search_console_search_volume/blob/ebed51123372b404a8090341ed50918b381becbd/code/code.js#L87

By adding this line, the cell will behave like the rest of the columns and the text will be correctly centered.
`padding: 18px 28px;`

**Comment by antoineeripret** [comment]
@Xyborg, thanks for the suggestion. 

I will leave the issue open and add it in the next release (date to be confirmed because I'll be on holidays soon).

**Comment by antoineeripret** [comment]
@Xyborg: change applied and submitted for review to the Chrome Store (version 0.2). Thanks for the suggestion!
