### ISSUE TITLE
En un search Console me funciona pero en otro no

### ISSUE THREAD

**Issue by jblanch2018** [antoineeripret/google_search_console_search_volume#6]
en el Search console mio personal me funciona pero el que usamos en la empresa no funciona. Supongo que puede ser por algun conflicto con algun plugin... lo pruebo y digo

**Comment by antoineeripret** [comment]
@jblanch2018: 

Si te funciona en una propiedad pero no en otra, es muy probable que tengas una palabra clave con un carácter especial que provoque un error con la API que usa la extensión. 

Podrías: 

- Abrir la página de la propiedad que comentas 
- Abrir el panel de desarrollador 
- Recargar la página 
- Esperar un poco, ir a la pestaña "Network" y buscar "surfer" 

![image](https://user-images.githubusercontent.com/9512616/123108023-57227600-d43a-11eb-9702-763ab76f5c24.png)

- Si mi teoría es correcta, deberías tener una solicitud en rojo, Copia y pega la URL de la solicitud aquí por favor. 

Gracias,

**Comment by jblanch2018** [comment]
No me sale ninguna url en rojo

![image](https://user-images.githubusercontent.com/45973003/123110969-f3388700-d412-11eb-8536-73b92b2b99a6.png)

**Comment by antoineeripret** [comment]
Raro :/ 

¿Me puedes copiar una de las URLs de tu pantallazo igualmente por favor?

**Comment by jblanch2018** [comment]
ahora he probado una propiedad bumeran.com.ar  y si que me sale una url en rojo y es esta

Request URL: https://db2.keywordsur.fr/keyword_surfer_keywords?country=ar&keywords=[%22chofer%20de%20camion%22,%22consultoras%20de%20trabajo%20en%20cordoba%22,%22empleos%20ramos%20mejia%22,%22empleo%20chofer%22,%22trabajos%20capital%20federal%22,%22musimundo%20trabaja%20con%20nosotros%22,%22bumeran%20san%20luis%22,%22empleo%20cajera%22,%22empleos%20en%20jujuy%22,%22empleo%20de%20limpieza%22,%22empleo%20nutricionista%22,%22trabajo%20freelance%22,%22busco%20trabajo%20la%20plata%22,%22trabajos%20en%20zona%20sur%22,%22personal%20de%20limpieza%22,%22empleo%20santa%20fe%22,%22empleos%20en%20san%20miguel%22,%22busco%20trabajo%20en%20cordoba%20capital%22,%22bolsa%20de%20trabajo%20capital%20federal%22,%22empleos%20lanus%22,%22trabajo%20en%20quilmes%22,%22empleos%20ezeiza%22,%22trabajo%20call%20center%22,%22bumeran%20konecta%22,%22empleos%20en%20lujan%22,%22atencion%20al%20cliente%22,%22eficasia%20argentina%22,%22ayudante%20de%20cocina%22,%22empleo%20seguridad%20e%20higiene%22,%22trabajo%20en%20san%20miguel%22,%22community%20manager%20trabajo%22,%22empleo%20en%20entre%20rios%22,%22agencia%20de%20trabajo%22,%22bolsa%20de%20trabajo%20cordoba%22,%22trabajos%20en%20quilmes%22,%22trabajo%20san%20miguel%22,%22remuneraci%C3%B3n%20bruta%20pretendida%22,%22alcanzo%20call%20center%22,%22trabajar%20desde%20casa%20argentina%22,%22empleos%20san%20justo%22,%22recepcionista%20part%20time%22,%22prosegur%22,%22empleos%20en%20mar%20del%20plata%22,%22empleos%20san%20nicolas%20de%20los%20arroyos%22,%22trabajos%20en%20neuquen%22,%22work%20digital%20&%20analogical%22,%22busco%20trabajo%20zona%20oeste%22,%22trabajo%20en%20san%20juan%22,%22empleos%20comodoro%20rivadavia%22,%22empleos%20bah%C3%ADa%20blanca%202021%22]

**Comment by antoineeripret** [comment]
Vale, creo que sé cuál es el problema. 

¿Me puedes confirmar que algunas de tus palabras clave contienen "&" por favor?

**Comment by jblanch2018** [comment]
si, tengo kw con &

![image](https://user-images.githubusercontent.com/45973003/123115124-3d6f3780-d416-11eb-9587-9d83172e91f6.png)

**Comment by antoineeripret** [comment]
Vale, aquí está el problema que no había anticipado. **Al tener un & en la palabra clave, rompe la API, que devuelve 200 pero con un error.** 

Acabo de hacer un commit en GitHub para arreglar el problema, pero no podré publicarlo en el Chrome Store antes de mi vuelta de vacaciones (en unas 3 semanas).

A partir de esta fecha, lo podrás usar en esta propiedad también.

**Comment by jblanch2018** [comment]
PErfecto. Disfruta de las vacaciones

**Comment by antoineeripret** [comment]
@jblanch2018: modificación hecha y mandada en revisión (v0.2) en el Chrome Store. ¡Gracias por la ayuda!
